### ISSUE TITLE
Allow for filtering distance by km in addition to miles

### ISSUE THREAD

**Issue by froboy** [open-y-subprojects/openy_map#7]
(Wonderfully...) YMCAs outside of the USA are taking notice of Open Y! While the map supports setting the default location, it does not allow for unit switching in case that location happens to be in the ... 99% of the world (this was not fact-checked) that uses the metric system.

- Add a setting on `admin/openy/settings/openy_map` to allow the map distance filter to use km instead of miles.
- Change the filter accordingly.

![Locations___YMCA_Canada](https://user-images.githubusercontent.com/238201/130502543-b5958c80-a367-4819-93a8-7cb9db2a3652.png)

**Comment by podarok** [comment]
this is done https://github.com/open-y-subprojects/openy_map/releases/tag/1.2
